[project]
name = "zandla"
version = "0.1.0"
description = "Robot learning with SO-101 robot arm."
requires-python = ">=3.12, <3.13"


dependencies = [
    "lerobot[feetech]==0.5.1",
    "torch==2.7.0",
    "torchvision",
    "torchaudio",
    "matplotlib",
    "requests",
    "huggingface",
    "transformers",
    "torchtyping",
    "hypothesis",
    "pytest",
    "chalk-diagrams",
    "ipython",
    "jupyter",
    "mujoco>=3.9.0",
    "dm_control",
    "gymnasium",
    "sentence-transformers>=5.6.1",
    "imageio-ffmpeg>=0.6.0",
    "pymunk<7.0.0",
]

[project.optional-dependencies]
pusht = [
    "gym-pusht",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
override-dependencies = [
    "torchcodec ; sys_platform == 'never'",
]


[tool.uv.sources]
chalk-diagrams = { git = "https://github.com/chalk-diagrams/chalk" }
# Optional configuration for uv
